name: tomorrowsthinkers
favicon: null
layout_spectrum: 0.8
title: Free education for Gifted Kids
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#6a5f4f'
    - '#2e1b12'
    - '#9d8364'
    - '#acb1ab'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
